### ISSUE TITLE
Make caret position algorithm more complete.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1704]
What should be done in this issue:
- [x] Should be able to create the caret by lyric and the index. -> Implemented in the #1705
- [x] Can remove the `CheckCaretGenerateType` in the test case because there's no need to check the generate type. -> Implemented in the #1714
- [x] Caret state is able to use the new interface. -> Implemented in the #1706
- [x] Make `PositionMovable()` protected because it can convert into the internal check. -> Implemented in the #1704
- [ ] (Optional)Move `PositionMovable` method in to the `IndexCaretPositionAlgorithm`.  -> Recorded in the #1747
  - Need to think about that because not movable might not only affected by index.

**Comment by andy840119** [comment]
Close due to remaining part are separated to the #1747.
