### ISSUE TITLE
Implement issue table in the lyric editor composer.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1728]
After #1685 has been implemented.
Guess it's time to implement this part.

There's are two ways to implement this part:
1. use the issue table.
2. re-write a new table for it.

![image](https://user-images.githubusercontent.com/9100368/201517467-542934df-d937-45c0-9fdb-c1f3fbf023a0.png)
Here's the table in the verify table.

**Comment by andy840119** [comment]
Need to think about the refactor part:
- Make the drawable to display the icon for the issue table. Maybe called something like "DrawableIssueIcon"
- Move LyricEditorTable into more generic location?
- Writing utils to get the lyric and lyric object from the issue.

**Comment by andy840119** [comment]
Maybe need those refactor steps:
- [x] Need to create the issue icon (maybe create new namespace named `Issues` in the table container). -> #1740
- [x] Need to move the `InvalidLyricToolTip` into the `Issues` namespace. -> #1741
- [x] Need to move the `IssueTable` from the `IssueSection` into parent namespace. -> #1741
- [x] Tooltip should include the icon and the description.
- [x] [Optional] Not really sure should create tooltip just for single issue. -> Not very sure what it means >_>
- [x] Make the issue table able to hover to show the truncate tip. -> Implemented in the #2039. Use `TruncatingSpriteText` to make sure that text in the issue table will show the truncate tip.
- [x] Let panel able to accept the section -> #1743

Implement part:
- [x] Implement the issue table for the panel area. -> #1743
- [x] Add the damn refresh button. -> #1746
  - [x] Should create method to update issue for single lyric only -> #1746

**Comment by andy840119** [comment]
Also, should think about should we use the same icon in those parts?
- Issue table in the right side.
- Issue table in the lyric composer table.
- Tooltip for lyric row.

If use the different icon set, means should make the tooltip for the issue table.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/202855291-a5c88d25-bce2-40c0-9efc-f1eea483d31a.png)
No result and scan effect can see how `NoResultsPlaceholder` did 🤔 ?

**Comment by andy840119** [comment]
Guess the issue table in the lyric editor is OK enough.
So close this issue.
