### ISSUE TITLE
Implement the classic stage editor

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1765]
Guess should implement the editor while thinking #1764 
And can start implement this shit after add the new layout class in the #1755.

prepare:
- [x] Classic layout modal implementation. -> Handle in the #1755.
- [ ] Design the figma page for it.
    - [ ] Not really sure will use the same screen for different layout? -> maybe just named classic layout editor screen.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/204128623-72c68fb9-b530-4cfa-83cc-12e70e4b5b52.png)
Maybe what is this shit looks like.

**Comment by andy840119** [comment]
诶不是
怎麼感覺沒有結束的一天

**Comment by andy840119** [comment]
todo:
- [ ] Implement classic stage generator.
- [x] Implement classic stage change handler. -> Implemented in the #1825.
- [x] Implement the checks for the stage category. -> Implemented in the #1826.

**Comment by andy840119** [comment]
Note:
Should implement the timing part for the #1828.

**Comment by andy840119** [comment]
todo:
- [ ] Need to think about should combine the layout and timing into single editor?
