### ISSUE TITLE
Implement page (or maybe called breath) edit mode in the lyric editor.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1766]
Inspired from #1764

https://youtu.be/alR4Ac9evFg?t=93
Should be useful to create "page mode" in the lyric editor.
Same page means user can sing the lyric with one breath.
Usually between 1~4 lyrics.

Benefit:
- Might let user not confused if they can see the page in the layout editor. It might be useful if user can decide the lyric position by breath.
    - classic layout 可能會根據這個規則進行格式設計
- Will be used in the scrolling layout mode.
- 未來的 layout 可以根據 page 進行參考

**Comment by andy840119** [comment]
需要思考:
- 如果有遇到多個 singer 輪流唱歌詞，可能會遇到 page 跳號的問題，或許應該要有 checks 來檢查這件事情

**Comment by andy840119** [comment]
Maybe can use page number * magic number(e.g. 21) % 360 to get the hue number

**Comment by andy840119** [comment]
Wait
Page can be designed as control point
Should be better to do that?

**Comment by andy840119** [comment]
If add the check:
- [x] Should check by the page interval. -> Implemented in the #1780.
- [x] Should check the same page amount? -> Implemented in the #1780.

**Comment by andy840119** [comment]
Also, should move those classes into more generic location:
- [x] Move the markdown component into editor-level -> Implemented in the #1766.
- [x] `EditModeSection<T>` and `LyricEditorSettings ` , should make another base class for all editor. -> Implemented in the #1785.
- [x] Move the issue table into more general namespace. -> Implemented in the #1787
- [x] Should move the `IssueSection` into more generic location. -> Implemented in the ##1787
- [ ] Screens/Edit/Beatmaps/Lyrics/Settings/Components
  - Should move the block section wrapper into more generic location, those classes should be able to serve the whole editor level.

**Comment by andy840119** [comment]
Should prepare:
- [x] service for able to verify the section. -> implemented in the #1793

Should implement those edit sections:
- [x] show all pages. -> Implemented in the #1797
- [x] Issue table -> implemented in the #1793
- [x] Switch edit mode section -> implemented in the #1793

**Comment by andy840119** [comment]
- [ ] Also, should write the generator for the page editor.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/208276262-818e10f8-2758-4c08-b501-d5175670666b.png)
Need to make some improvements:
- [x] Should be able to drag the time to change the page to change the time. -> Implemented in the #1802.
- [ ] Should be able to click the `page-related` issue to select the blueprint.
- [ ] Should be able to click the `lyric-related` issue to select the blueprint.
- [ ] Should show the time marker. Not really sure should follow recording or adjust time-tag did?
- [x] Fix the pages order is not correct(both section and the blueprint container). -> Implemented in the #1802.
- [ ] Add the create and remove botton at the bottom right of the page editor.
- [ ] [Optional] Show the zoom level at the bottom right of the page editor.
- [ ] Separate the generate and the edit section.

**Comment by andy840119** [comment]
阿不是
issue 怎麼會自己繁殖?

**Comment by andy840119** [comment]
Implemented, but not ready for use.
