### ISSUE TITLE
Think about how to deal with timing info for the classic stage info.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1828]
Very not sure now to implement this shit.
Might need to adjust the start and end time in the `ClassicStageInfo` i guess.

Mark as part of #1755 because it will be a part of classic stage info.

What's need to be done:
- [x] Implement the timing-info to store the time. -> Implemented in the #1830.
- [x] Implement the change handler for able to edit the timing info. -> Implemented in the #1831
- [x] Implement the check to check invalid info. -> Implemented in the #1837.

**Comment by andy840119** [comment]
https://youtu.be/alR4Ac9evFg?t=93
Guess it's time to check the video and think about is there any roles for the timing.
Should be better not to let user able to edit the timing.

**Comment by andy840119** [comment]
The structure might like the page info.
Will have list of the timing info.
And the timing info will looks like:
- List<ID> DisappearedLyrics
- double currentTime
- List<ID> ShowingLyrics.

Not really sure stage category can handle this one?
Very not sure, maybe not.
Guess need to write a new class for this shit.

Also, should have the checks:
- Check that every lyric should have the start and end time.
- Check that there's no ids that not in the list.
- Timing info should include start or end lyric id.
- [Optional] Check overlapping time, not really sure should check this shit by the layout row number?

**Comment by andy840119** [comment]
~~Wait, not really sure should record the id, or can easily query by the time?~~
Should be not possible to query by time i guess?

Or by layout id?
Not very sure also 😢 

[update]
Guess should be safe by lyric id.
User will not expect that change layout mapping will break the timing info.

**Comment by andy840119** [comment]
Also, Mark the timing point as special colour if this shit does not have start or end lyric mapping.

**Comment by andy840119** [comment]
And need to think about the time in the timing info should be absolute or be relative to the some lyric's time.

[Note]
we can save the absolute time and reference lyric id in the timing info, but able to adjust and sync in the editor.

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/211156636-37853ce9-f111-437a-b663-e3fa94baa233.png)
沒有 commit 的天數手指頭數得出來
幹您老師，把假日還我

**Comment by andy840119** [comment]
The format will be changed by #1836.

https://karaoke-dev.notion.site/Classic-stage-timing-info-05350c50c19d4d1fbccbeb5b9b0b2e07
Here's the document explain about why doing this.

**Comment by andy840119** [comment]
Guess can close this issue because metadata part has been implemented.
