### ISSUE TITLE
Auto-generate control component for the auto-generate config.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#1869]
![image](https://user-images.githubusercontent.com/9100368/222934770-0e2fb21d-b5e6-4d10-87ec-323208c81d88.png)
![image](https://user-images.githubusercontent.com/9100368/222934772-4f3c5402-c501-48a8-bce9-872310628dc5.png)
Like the control in the mod and the skin editor, should be possible to auto-generate the control for the auto-generator and the auto-detector config.

And here's the step:
- [x] Remove the dialog. The dialog will not be used anymore. -> Implemented in the #1870.
- [x] Change the property in the config to the bindable. Also, should add the `SettingSource` attribute. -> Implemented in the #1871.
  - [x] Note that should create the `SettingCategory` attribute for able to generate the control with different category. Implemented in the #1871.
- [x] Use the auto-generate resource instead. -> Implemented in the #1873.
  - [x] Should create config's own `SettingSourceExtensions` because we want to generate the control  with `LabelledTextBox` -> Implemented in the #1872.
  - [ ] Add a test case to make sure that serializer/deserializer is working.

**Comment by andy840119** [comment]
Need to think about will only this part use the `SettingCategory ` in the editor?
Should make this more generic if will be used in the other part.

**Comment by andy840119** [comment]
Note the benefit is use the bindable:
- It might be easy to roll-back to the default value by just a click.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/9100368/223029222-12f8aa94-6a23-41c6-b291-7379292dd95e.png">

Also:
- [x] Think about should assign the default value into the property or `CreateDefaultValue()` interface? We might need the config instance that all value should be initialize(like false, zero or something). -> Guess answer is in the #1871 ?

**Comment by andy840119** [comment]
Guess this issue can be closed now because most of issues has been implemented.
Serializer/deserialize issue can be fixed after.
