### ISSUE TITLE
Move the romaji to the time-tag.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#2004]
Not very sure about that but it will be useful to show the romaji-only lyric if we make every char has it's own romaji.

**Comment by andy840119** [comment]
我又懶了，用一下中文好了

![image](https://github.com/karaoke-dev/karaoke/assets/9100368/08952de6-3b7f-4981-beb6-3fc8caa238d3)
目前 romaji 的設計是歌詞的一小段會
而不是每一個字元都有對應的 romaji
如果有一天需要做出只會顯示 romaji 的歌詞，會有 time-tag 對不上的問題

Recorded in here:
https://karaoke-dev.notion.site/tomaji-text-tag-time-tag-8c351278062a470fa4449a9172b3ad02?pvs=4

**Comment by andy840119** [comment]
另外，或許需要設計更好的 tool，去 combine and separate the romaji?

**Comment by andy840119** [comment]
Guess:
1. Remove the romaji text class and add the romaji property into the time-tag.
2. Add the `RomajiContinuous` property in the time-tag.

想法是一個 time-tag 通常對應一個音節，romaji也有類似的分段方式

**Comment by andy840119** [comment]
https://randulakoralage82.medium.com/format-your-net-code-with-git-hooks-a0dc33f68048
here's the article about how to set-up the pre-commit in the C# project.

**Comment by andy840119** [comment]
Remaining:
- [x] Tag helper should be able to support the text within the time-tag. -> Implemented in the #2076
- [ ] Should be able to support save/load the text in the time-tag serializer. -> Moved into #2278
- [x] Implement the auto-generator for able to fill the romaji to the time-tag. -> Implemented in the #2077
- [x] Should be able to edit the romaji text and the initial romaji property in the change handler. -> Implemented in the #2079
- [x] Add time-tag romaji auto-generate logic for the time-tag change handler. -> Implemented in the #2004.

**Comment by andy840119** [comment]
Wait.
Note has `Ruby text` property.
Not very sure will have `Romaji` property in the note also? -> guess should be get from time-tag, or note should have time-tag index?

**Comment by andy840119** [comment]
Remaining part(editor):
- [x] Should edit the property from the time-tag, not the romaji class. #2136
- [x] Adjust the import step. Auto-generate romaji should be after generate time-tag. Or just remove this step. #2137
- [x] Remove the old romaji generator(and the generator). #2138
- [x] Remove the change handler. #2139
- [x]  Re-write the new checks to check the romaji from the time-tag. #2140
- [x] Should be able to get the romaji text position in the `IPreviewLyricPositionProvider`.

Remaining part(drawable):
- [ ] Support convert the ruby text from the time-tag into position text. -> not very sure what does this means?

Remaining part(object):
- [x] Remove the RomajiTag class.
- [x] Remove the ITextTag interface.
- [x] Remove any "text tag" wording in this project.
- [x] `RomajiTag` should be renamed to the `Romaji` or `TimeTagRomaji`

**Comment by andy840119** [comment]
Most issue is implemented.
