### ISSUE TITLE
Should be able to drag the main lyric text to generate the ruby/romaji text.

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#2007]
<img width="693" alt="image" src="https://github.com/karaoke-dev/karaoke/assets/9100368/2aee131e-1d1a-4f24-b23d-7a039221ad2a">

As title, instead of typing the start and end index in here, should be able to drag the the main text to create the ruby/romaji with start and end index.

**Comment by andy840119** [comment]
Guess can implement after #2008?

**Comment by andy840119** [comment]
Guess should wait after #2009?

[Update]
Implemented

**Comment by andy840119** [comment]
After we have sample to drag range of the lyric and do the action (see: #2099)
Maybe it's a good start to continue this issue.

**Comment by andy840119** [comment]
Remaining part:
- [x] Guess should be better to have the pop-up `with ruby text input and create button` after select the range of the text. #2126
  - [x] caret state should have bindable for able to record the release state. #2125
- [x] Need to show the popover if click the ruby tag, like how note edit area did. #2131
- [x] Create a hot-key for able to create ruby-tag if select the range. -> will open the popover after click or select range of the main text.
  - E.g. create the ruby tag if select the range of the text and press "enter".
  - Also, should show the description by edit mode switcher subsection.
- [x] It's time to remove the "add ruby" and "add romaji" button. #2128

**Comment by andy840119** [comment]
Guess it's enough to close this issue.
