### ISSUE TITLE
List all the editor and big progress

### ISSUE THREAD

**Issue by andy840119** [karaoke-dev/karaoke#248]
Because this ruleset has some small editor, so list to here to let me or other visitor to know what's have now: 

- Exist karaoke editor(note editor): 
  - Create/delete notes.
  - Drag notes into target position.
  - Assign lyric's layout (relative position).
  - Implement regular way like other ruleset do.

- Lyric maker(time tag editor)
  - Create/delete lyric.
  - Change the order or lyric.
  - Add/remove time tag for each lyric.
  - Edit time tag's time(by pressing button in target time or dragging).

- Layout editor
  - Edit list of lyric's position.

- Style editor
  - Edit target singer's lyric and note's style.     
    If lyric is assigned by some singer, lyric and note will apply style.

- Singer editor
   - Create/delete list of singer.
   - Assign which singer sings which lyric.

- Translator editor
   - Edit lyric's translate with multi language support.

- Ruby/romaji editor
   - Edit ruby/romaji in each lyric.

- Import lyric
   - Has list of step to let user import lyric / create ruby / create time-tag at the same time.

**Comment by andy840119** [comment]
And what's waiting for implementing now : 

- Exist karaoke editor(note editor):
  - [ ] Auto-adjust note's position by singer's voice

- Lyric maker(time tag editor):
  - [x] Replace as main editor(or will be combined and switchable) (in #364).
  - [x] [doing]Add time-tag display. (in #284)
  - [x] [doing]Switch mode (View, Edit, Record, EditTimeTag)

- Layout editor
  - [ ] Implement preview.

- Style editor
  - [ ] Implement preview.

- Singer editor
  - [x] `[doing]Fix blueprint is disappear in new lazer version(because it don't have HitObjectComposer).`

- Translator editor
  - [x] [doing]Use CultureInfo instead of exist language mapping.
  - [x] `[doing]Implement adding button to manage list of language.`

- Ruby/romaji editor
  - [x] Implement add/remove ruby/romaji.

- Import lyric
  - [x] [doing]Set each lyric's Language(adding language id property and manager).  #258 
  - [x] [doing]Pre-implement auto-calculate ruby page.
  - [x] [doing]Pre-implement auto-calculate time-tag page.

**HighLight** selection is planning to implement/fix recently.
